# This is a basic workflow to help you get started with Actions

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    INSTANCE: Writerside/hi
    ARTIFACT: webHelpHI2-all.zip
    DOCKER_VERSION: 2.1.1479-p3869

    ALGOLIA_ARTIFACT: algolia-indexes-HI.zip

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
              artifacts/${{ env.ARTIFACT }}
              artifacts/report.json
          retention-days: 7

      # Add the step below to upload Algolia indexes
      - name: Upload algolia-indexes
        uses: actions/upload-artifact@v3
        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

# Add the job below and artifacts/report.json on Upload documentation step above if you want to fail the build when documentation contains errors
  test:
    # Requires build job results
      needs: build
      runs-on: ubuntu-latest

      steps:
          - name: Download artifacts
            uses: actions/download-artifact@v1
            with:
              name: docs
              path: artifacts

          - name: Test documentation
            uses: JetBrains/writerside-checker-action@v1
            with:
              instance: ${{ env.INSTANCE }}
